# Generated by Django 3.1.7 on 2021-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Song name'),
        ),
    ]
